-
  name: Deploy Web Appilocation
  hosts: target1, target2
  tasks:
    - name: Install dependencies
      apt:
        name: '{{ item }}'
        state: installed
        with_items:
          - python
          - python-setuptools
          - python-dev
          - build-essential
          - python-pip
          - python-mysqldb
          - git
    - name: Install Mysql database
      apt:
        name: '{{ item }}'
        state: installed
        with_items:
          - mysql-server
          - mysql-client
    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Create Application Database
      mysql_db: name=employee_db state=present

    - name: Create Application DB User
      mysql_user:
        name: db_user
        password: PasswOrd
        priv: '*.*:ALL'
        state: present
    - name: Install Python Flask dependencies
      pip:
        name: '{{ items }}'
        with_items:
          - flask
          - flask-mysql

    - name: Copy web-server code
      git:
        repo: 'https://github.com/mmumshad/simple-webapp.git'
        dest: /opt/

    - name: Run web-server
      shell: FLASK_APP=/opt/simple-webapp/app.py flask run --host=0.0.0.0