-
  name: Deploy Web Appilocation
  hosts: target1, target2
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages1 }}"

    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml

