packages1:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
      - libmysqlclient-dev
      - python-pymysql
      - git
packages2:
  - mysql-server
  - mysql-client
db_name: employee_db
db_user: db_user
db_password: Passw0rd